version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: timesheet_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: 
      context: ./Timesheet.Api
      dockerfile: Timesheet.Web/Dockerfile
    container_name: timesheet_backend
    env_file:
      - ./Timesheet.Api/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    ports:
      - "5000:8080"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./Timesheet.Ui
      dockerfile: Dockerfile
    container_name: timesheet_frontend 
    environment:
        # SET THE API URL TO THE BACKEND SERVICE
      - VITE_API_URL=http://localhost:5000/api 
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: