version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: timesheet_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: 
      context: ./Timesheet.Api
      dockerfile: Timesheet.Web/Dockerfile
    container_name: timesheet_backend
    env_file:
      - ./Timesheet.Api/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    expose:
      - "8080"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./Timesheet.Ui
      dockerfile: Dockerfile
    container_name: timesheet_frontend 
    environment:
        # SET THE API URL TO THE BACKEND SERVICE
      - VITE_API_URL=https://localhost/api 
    expose:
      - "5173"
    depends_on:
      - backend
    restart: always

  caddy:
    image: caddy:2-alpine
    container_name: timesheet_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config: